### ISSUE TITLE
Internal method in InlineMenuRowBuilder is public

### ISSUE THREAD

**Issue by bo0tzz** [JavaTelegramBot-API/JavaTelegramBot-API#63]
[This method](https://github.com/zackpollard/JavaTelegramBot-API/blob/2e25056b4b7b2b9394be18d04d4adcbcefdbc758/src/main/java/pro/zackpollard/telegrambot/api/menu/InlineMenuRowBuilder.java#L32) is public, while it should probably be private?
@mkotb

**Comment by nickrobson** [comment]
@bo0tzz not gonna be done as removing it would require 2.0.0 according to semantic versioning

**Comment by mkotb** [comment]
This was intended due to a little design issue. There are one or two methods that are "caller dependent" and left public through the menu API, due to the builder's complex backend. I left this without caller dependence in case a developer wants to implement their own button implementation, and add it manually.

**Comment by bo0tzz** [comment]
Ah, right. Don't mind what I said then.
